# Auto time-based profiles
max-gamma = 150

profile {
    time = 07:00
    identity = true  # Neutral daylight
}

profile {
    time = 18:00     # Evening warm
    temperature = 4000
    gamma = 0.95
}
